server:
  port: 9999

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

zuul:
  routes:
    cart:
      path: /carts/**
      url: http://www.umasuo.com
    category:
      path: /categories/**
      url: http://localhost:8082/
    auth:
      path: /auth/**
      url: http://localhost:8083/
    customer:
      path: /customers/**
      url: http://customers:8084/
    inventory:
      path: /inventory/**
      url: http://localhost:8085/
    order:
      path: /orders/**
      url: http://localhost:8086/
    payment:
      path: /payments/**
      url: http://localhost:8087/
    product:
      path: /products/**
      url: http://localhost:8088/
    product-type:
      path: /product-types/**
      url: http://localhost:8089/

authentication:
  service:
    uri: http://localhost:9091/