kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: dev
  name: api-gateway-admin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: api-gateway-admin
    spec:
      containers:
      - name: api-gateway-admin
        image: reactivesw/api-gateway-admin:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: server_port
          value: "80"
        - name: spring_cloud_config_uri
          value: http://reactivesw-config