kind: List
apiVersion: v1
items:
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: api-gateway-admin
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: api-gateway-admin
      spec:
        containers:
        - name: api-gateway-admin
          image: reactivesw/api-gateway-admin:0.0.1
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          env:
          - name: server_port
            value: "80"
- kind: Service
  apiVersion: v1
  metadata:
    name: api-gateway-admin
    labels:
      name: api-gateway-admin
  spec:
    type: NodePort
    ports:
    - port: 80
      targetPort: 80
      nodePort: 30009
    selector:
      name: api-gateway-admin

